version: '3.4'

services:
  teddit:
    image: gitea.arleskog.se/albertarleskog/teddit:latest
    networks:
      - apps
      - teddit
    expose:
      - 8080
    environment:
      - DOMAIN=teddit.arleskog.se
      - USE_HELMET=true
      - USE_HELMET_HSTS=true
      - USE_VIEW_CACHE=true
      - TRUST_PROXY=true
      - THEME=auto
      - REDIS_HOST=redis
    depends_on:
      - redis
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://localhost:8080/about || exit 1'
      interval: 60s
      timeout: 5s
      retries: 3
  redis:
    networks:
      - teddit
    image: redis:6.2.5-alpine
    tmpfs:
      - /var/lib/redis
    command: 
      - redis-server
    environment:
      - REDIS_REPLICATION_MODE=master

networks:
  apps:
    external: true
  teddit:
