---
version: "3"

services:
  drone:
    image: drone/drone:2
    container_name: drone
    environment:
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID:?}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET:?}
      - DRONE_USER_FILTER=${DRONE_USER_FILTER:?}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET:?}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST:?}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO:?}
    restart: unless-stopped
    networks:
      - apps
    volumes:
      - drone:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.drone.entrypoints=websecure

networks:
  apps:
    external: true

volumes:
  drone:
