---
version: '3.3'

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - config:/config
    networks:
      - apps
      - authelia
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.entrypoints=websecure
      - traefik.http.middlewares.authelia.forwardauth.address=http://authelia.apps:9091/api/verify?rd=https://authelia.${DOMAIN:?}
      - traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email
    expose:
      - 9091
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - TZ=${TZ:-Europe/Stockholm}
      - AUTHELIA_JWT_SECRET=${JWT_SECRET:?}
      - AUTHELIA_SESSION_SECRET=${SESSION_SECRET?}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${STORAGE_ENCRYPTION_KEY:?}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD=${AUTHENTICATION_BACKEND_LDAP_PASSWORD:?}
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET=${IDENTITY_PROVIDERS_OIDC_HMAC_SECRET:?}
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE=/config/.IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    networks:
      - authelia
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/Stockholm}

networks:
  apps:
    external: true
  authelia:

volumes:
  config:
  redis:
