version: '3'

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:1.17.3
    expose:
      - 3000 # Web
      - 22 # SSH
    ports:
      - 443:3000
      - 2222:22
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /volumes/gitea:/data
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
