version: '3'

services:
  cc:
    image: mpepping/cyberchef:latest
    restart: unless-stopped
    container_name: cc
    networks:
      - apps
    expose:
      - 8000

networks:
  apps:
    external: true
