---
version: '3'

services:
  cc:
    image: mpepping/cyberchef
    restart: unless-stopped
    container_name: cc
    networks:
      - apps
    expose:
      - 8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.cc.entrypoints=websecure

networks:
  apps:
    external: true
