---
version: '3'

services:
  ytdl:
    image: 'tzahi12345/youtubedl-material:latest'
    container_name: ytdl
    environment:
      - ALLOW_CONFIG_MUTATIONS=true
      - ytdl_mongodb_connection_string=mongodb://db:27017
      - ytdl_use_local_db=false
      - write_ytdl_config=true
    depends_on:
      - db
    volumes:
      - config:/app
      - /data/media/youtube:/youtube
    expose:
      - 17442
    networks:
      - apps
      - ytdl
    labels:
      - traefik.enable=true
      - traefik.http.routers.ytdl.entrypoints=websecure
      - traefik.http.routers.ytdl.middlewares=authelia@docker

  db:
    image: mongo
    networks:
      - ytdl
    volumes:
      - 'db:/data/db'

volumes:
  config:
  db:

networks:
  apps:
    external: true
  ytdl:
