version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD='mepR3DsQQacklXmtRxfb/dIo0Q5l8iU5J8MazGfBvbc='
    volumes:
      - /volumes/postgres:/var/lib/postgresql
    networks:
      - postgres

networks:
  postgres:
    external: true
