---
version: '3.7'

services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    networks:
      - apps
      - searxng
    expose:
      - 8080
    volumes:
      - config:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=https://searxng.${DOMAIN:?}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    labels:
      - traefik.enable=true
      - traefik.http.routers.searxng.entrypoints=websecure

  redis:
    image: redis:alpine
    command: redis-server --save "" --appendonly "no"
    restart: unless-stopped
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

volumes:
  config:

networks:
  apps:
    external: true
  searxng:
