version: '3'

services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    networks:
      - apps
      - searxng
    expose:
      - 8080
    volumes:
      - /volumes/searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=https://searxng.arleskog.se/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    depends_on:
      - redis
  redis:
    image: redis:alpine
    command: redis-server --save "" --appendonly "no"
    restart: unless-stopped
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  apps:
    external: true
  searxng:
